Update gulp sample.
GoogleChrome/workbox-microsite pull request #23
Opened 2017-05-12 19:17 UTC by jpmedley

2017-05-12 19:35 UTC, jeffposnick requested changes

2017-05-12 19:35 UTC, jeffposnick commented on src/get-started/gulp.md
> +install the module then cut and paste the code sampel
sampel -> sample

2017-05-12 19:35 UTC, jeffposnick commented on src/get-started/gulp.md
> +    npm install workbox-build --save
This should be `--save-dev`, since `workbox-build` isn't a runtime dependency.

2017-05-12 19:35 UTC, jeffposnick commented on src/get-started/gulp.md
> +    ```gulp.task('test', () => {
'test' -> 'generate-sw' (or something similar).

2017-05-12 19:35 UTC, jeffposnick commented on src/get-started/gulp.md
> +          rootDirectory: './app/',
`rootDirectory` is no more. It's been supplanted by `globDirectory`.

2017-05-12 19:45 UTC, jpmedley commented
@jeffposnick PTAL

2017-05-12 23:02 UTC, jeffposnick approved these changes

2017-05-12 23:45 UTC, jeffposnick requested changes
Actually, one thing that I realized that is missing (after reviewing the npm scripts examples) is to make sure the developer knows that the new gulp task for generating the service worker should always be run as the last step in each build.

I.e. instead of presenting it as a standalone task or something that you might run once and forget it, presenting it as a task that is run unconditionally as the last step in a larger build pipeline.

2017-05-13 01:59 UTC, jeffposnick commented
Here's an example of calling a `bundle-sw` task inside a larger gulp build process, if that helps: https://github.com/GoogleChrome/application-shell/blob/ifixit-pwa/ifixit-pwa/gulpfile.js#L165

(That particular example is still using an older method of creating the SW file, so don't focus on the content of the `bundle-sw` task. I just wanted to point out the way the build pipeline is structured, with the service worker generation as the last step.)

2017-05-13 15:10 UTC, jpmedley commented
@jeffposnick PTAL

2017-05-13 17:38 UTC, jeffposnick approved these changes

2017-05-13 19:23 UTC, merged